name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Verify pytest installation
        run: python -m pytest --version

      - name: List installed packages
        run: pip list

      - name: Check Python path
        run: |
          which python
          python -m site

      - name: Ensure pytest is in PATH
        run: |
          echo $PATH
          python -c "import os; print(os.environ['PATH'])"

      - name: Run a simple test
        run: |
          echo "def test_simple(): assert 1 + 1 == 2" > test_simple.py
          python -m pytest test_simple.py

      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/predictions-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/predictions-api:latest
